kotlin.code.style=official
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.mpp.applyDefaultHierarchyTemplate=true

android.useAndroidX=true
android.enableJetifier=true

# Gradle
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true


GROUP=sk.ainet.graphviz
VERSION_NAME=0.0.1

POM_DESCRIPTION=kmp-graphviz

POM_URL=https://github.com/sk-ai-net/kmp-graphviz/
POM_SCM_URL=https://github.com/sk-ai-net/kmp-graphviz
POM_SCM_CONNECTION=scm:git:git@github.com:sk-ai-net/kmp-graphviz.git
POM_SCM_DEV_CONNECTION=scm:git:ssh@github.com:sk-ai-net/kmp-graphviz.git

POM_LICENCE_NAME=MIT License
POM_LICENCE_URL=https://mit-license.org/
POM_LICENCE_DIST=repo

POM_DEVELOPER_ID=sk-ai-net
POM_DEVELOPER_NAME=SKaiNET development team
POM_DEVELOPER_URL=https://github.com/sk-ai-net/

mavenCentralPublishing=true
mavenCentralAutomaticPublishing=true
signAllPublications=false


POM_ARTIFACT_ID=graphviz
POM_NAME=KMP port of graphviz